/* tslint:disable */
/* eslint-disable */
/**
 * Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileDto
 */
export interface FileDto {
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    contentType: string;
    /**
     * 
     * @type {number}
     * @memberof FileDto
     */
    length: number;
    /**
     * 
     * @type {Date}
     * @memberof FileDto
     */
    uploadedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    uploader: string;
}

/**
 * Check if a given object implements the FileDto interface.
 */
export function instanceOfFileDto(value: object): value is FileDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('uploadedAt' in value) || value['uploadedAt'] === undefined) return false;
    if (!('uploader' in value) || value['uploader'] === undefined) return false;
    return true;
}

export function FileDtoFromJSON(json: any): FileDto {
    return FileDtoFromJSONTyped(json, false);
}

export function FileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'fileName': json['fileName'],
        'contentType': json['contentType'],
        'length': json['length'],
        'uploadedAt': (new Date(json['uploadedAt'])),
        'uploader': json['uploader'],
    };
}

  export function FileDtoToJSON(json: any): FileDto {
      return FileDtoToJSONTyped(json, false);
  }

  export function FileDtoToJSONTyped(value?: FileDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'fileName': value['fileName'],
        'contentType': value['contentType'],
        'length': value['length'],
        'uploadedAt': ((value['uploadedAt']).toISOString()),
        'uploader': value['uploader'],
    };
}

